### PR TITLE
Added problem 2 and problem isnt ready yet 

### PR DESCRIPTION
**Pull request by ModusMorris**

### CODE REVIEW

**Comment by honnigmelone** [comment]
Nice work, I would still recommend to have similar structure. That we either have every filter as a single independent  .py file  in the base rep or have all filters in a single file (for example the nam). We can still do that later so i will just merge it now.

**Review by honnigmelone — APPROVED** [review]

**Comment by Salt-is-leaving** [comment]
Great job! FYI some insights to the Traceback error you can get by running your script in --debug mode.

**Review by Salt-is-leaving — APPROVED** [review]
Looks clean, approved.

**Review by Salt-is-leaving — APPROVED** [review]
Well done 👍

**Review by Salt-is-leaving — APPROVED** [review]
Ok, let's merge the entire branch Angular_problem now

**Pull request merged**
